# Generated by Django 4.0.6 on 2022-07-12 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='anio',
            field=models.IntegerField(null=True, verbose_name='Año'),
        ),
    ]
