# Generated by Django 4.0.6 on 2022-07-12 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_remove_libro_portada_libro_imagen'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Libro',
        ),
    ]
